# Generated by Django 5.1.4 on 2025-03-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payorder',
        ),
    ]
