# Generated by Django 5.1.4 on 2025-02-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='checkout',
        ),
    ]
