# Generated by Django 5.1.4 on 2025-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=True, help_text='Designates whether the user is a customer.'),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
